####################################### INFORMACIÓN DEL PLUGIN #####################################################
# Nombre del Plugin: SDUBCore - (Core de SurvivalDub).                                                             #
# Autor: RAAM150.                                                                                                  #
# Perfil Bukkit: http://dev.bukkit.org/profiles/RAAM150/                                                           #
# Perfil Spigot: https://www.spigotmc.org/members/raam250.27210/                                                   #
# Perfil SurvivalDub: https://www.survivaldub.com/members/raam150.16501/                                           #
# Descripción: Plugin Core del servidor SurvivalDub.                                                               #
####################################################################################################################

###################################### DONDE REPORTAR BUGS/SUGERENCIAS #############################################
# Cualquier sugerencia del plugin o bug encontrado reportaselo al creador del plugin (RAAM150).                    #
# Contacto:                                                                                                        #
#  Skype: RAAM150.                                                                                                 #
#  Twitter: RAAM150.                                                                                               #
#  MSG privado en SurvivalDub: https://www.survivaldub.com/members/raam150.16501/                                  #
####################################################################################################################

  
# Formato de los mensajes a la hora de envio, para jugadores normales y el staff.  
Formato_Mensaje:
  Jugador: '%jugador &7» &f%mensaje'
  Staff: '%jugador &7» &b%mensaje'
  
# Mantenimiento del servidor (WhiteList) nadie entra. Permiso (warcraft.mantenimiento.bypass).
Modo_Mantenimiento:
  # Mantenimiento está activo o no.
  Mantenimiento: false
  # Mensaje cuando el servidor está en mantenimiento
  Mensaje: '&4* &cMantenimiento &4*\n\n&7El servidor se encuentra en mantenimiento.\n\n&6» &aMás información en: &e&nwarcraft.com'

# Eventos que ocurren dentro del servidor.
Eventos_Servidor:
  # Lluvia del servidor.
  Lluvia: true
  # Jugadores sufren daños o no.
  Daños: true
  
# Eventos que ocurren con los jugadores.
Eventos_Jugador:
  # El jugador no puede tirar Items.
  No_Tirar_Items: true
  # El jugador no puede recoger Items.
  No_Recoger_Items: true
  # El jugador no puede romper bloques.
  No_Romper_Bloques: true
  # El jugador no puede poner/colocar bloques.
  No_Poner_Bloques: true
  # El jugador no sufre de hambre (Su barra de comida no baja).
  No_Hambre: true
  # El jugador no puede mover items de su inventario.
  No_Mover_Inventario: true

# Utilidades para el uso de jugadores o el servidor.
Utilidades:
  # Crear ficheros yml para los jugadores.
  Crear_Datos: true
  # Permisos para los eventos de Jugador.  
  Permisos: true
  # Permisos por mundos para eventos de Jugadores.  
  Permisos_Mundos: true
  
# Lugar de spawn (NO TOCAR CUANDO SE HAYA COLOCADO) / Coordenadas
Spawn:
  Mundo_Nombre: 'MUNDO'
  X: 0.0D
  Y: 0.0D
  Z: 0.0D
  PITCH: 0.0F
  YAW: 0.0F